// SPDX-License-Identifier: MIT
// Copyright (c) 2026 MoonshotAI
// Copyright (C) 2026, Advanced Micro Devices, Inc. All rights reserved.

#include "aiter_stream.h"
#include "flash_kda.h"
#include "rocm_ops.hpp"

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m)
{
    AITER_SET_STREAM_PYBIND
    m.def("flash_kda_fwd_hip",
          &aiter::flash_kda_fwd_hip,
          "Native FlashKDA forward for gfx942/gfx950 (writes outputs in place)",
          py::arg("q"),
          py::arg("k"),
          py::arg("v"),
          py::arg("g"),
          py::arg("beta"),
          py::arg("out"),
          py::arg("workspace"),
          py::arg("A_log"),
          py::arg("dt_bias"),
          py::arg("initial_state"),
          py::arg("final_state"),
          py::arg("cu_seqlens"),
          py::arg("scale"),
          py::arg("lower_bound"),
          py::arg("has_initial_state"),
          py::arg("output_final_state"),
          py::arg("is_varlen"));
    m.def("flash_kda_fwd_hip_raw",
          &aiter::flash_kda_fwd_hip_raw,
          "Internal validated-pointer FlashKDA forward fast path",
          py::arg("q_ptr"),
          py::arg("k_ptr"),
          py::arg("v_ptr"),
          py::arg("g_ptr"),
          py::arg("beta_ptr"),
          py::arg("out_ptr"),
          py::arg("workspace_ptr"),
          py::arg("A_log_ptr"),
          py::arg("dt_bias_ptr"),
          py::arg("initial_state_ptr"),
          py::arg("final_state_ptr"),
          py::arg("cu_seqlens_ptr"),
          py::arg("B"),
          py::arg("T"),
          py::arg("H"),
          py::arg("N"),
          py::arg("workspace_bytes"),
          py::arg("scale"),
          py::arg("lower_bound"),
          py::arg("has_initial_state"),
          py::arg("output_final_state"),
          py::arg("is_varlen"),
          py::arg("state_fp32"),
          py::arg("device_id"),
          py::arg("stream_ptr"));
    m.def("flash_kda_fwd_hip_raw_v2",
          &aiter::flash_kda_fwd_hip_raw_v2,
          "Internal validated-pointer FlashKDA forward with routing hint",
          py::arg("q_ptr"),
          py::arg("k_ptr"),
          py::arg("v_ptr"),
          py::arg("g_ptr"),
          py::arg("beta_ptr"),
          py::arg("out_ptr"),
          py::arg("workspace_ptr"),
          py::arg("A_log_ptr"),
          py::arg("dt_bias_ptr"),
          py::arg("initial_state_ptr"),
          py::arg("final_state_ptr"),
          py::arg("cu_seqlens_ptr"),
          py::arg("B"),
          py::arg("T"),
          py::arg("H"),
          py::arg("N"),
          py::arg("workspace_bytes"),
          py::arg("scale"),
          py::arg("lower_bound"),
          py::arg("has_initial_state"),
          py::arg("output_final_state"),
          py::arg("is_varlen"),
          py::arg("state_fp32"),
          py::arg("device_id"),
          py::arg("stream_ptr"),
          py::arg("max_seqlen_upper_bound"));
    m.def("flash_kda_fwd_hip_raw_v3",
          &aiter::flash_kda_fwd_hip_raw_v3,
          "Internal validated-pointer FlashKDA forward with GVA head geometry",
          py::arg("q_ptr"),
          py::arg("k_ptr"),
          py::arg("v_ptr"),
          py::arg("g_ptr"),
          py::arg("beta_ptr"),
          py::arg("out_ptr"),
          py::arg("workspace_ptr"),
          py::arg("A_log_ptr"),
          py::arg("dt_bias_ptr"),
          py::arg("initial_state_ptr"),
          py::arg("final_state_ptr"),
          py::arg("cu_seqlens_ptr"),
          py::arg("B"),
          py::arg("T"),
          py::arg("H"),
          py::arg("N"),
          py::arg("workspace_bytes"),
          py::arg("scale"),
          py::arg("lower_bound"),
          py::arg("has_initial_state"),
          py::arg("output_final_state"),
          py::arg("is_varlen"),
          py::arg("state_fp32"),
          py::arg("device_id"),
          py::arg("stream_ptr"),
          py::arg("max_seqlen_upper_bound"),
          py::arg("H_q"));
}
